/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pdaxrom_cctools_sdlplugin_Utils */

#ifndef _Included_com_pdaxrom_cctools_sdlplugin_Utils
#define _Included_com_pdaxrom_cctools_sdlplugin_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pdaxrom_cctools_sdlplugin_Utils
 * Method:    setEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_pdaxrom_cctools_sdlplugin_Utils_setEnv
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_pdaxrom_cctools_sdlplugin_Utils
 * Method:    unSetEnv
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pdaxrom_cctools_sdlplugin_Utils_unSetEnv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pdaxrom_cctools_sdlplugin_Utils
 * Method:    getEnv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pdaxrom_cctools_sdlplugin_Utils_getEnv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pdaxrom_cctools_sdlplugin_Utils
 * Method:    chDir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pdaxrom_cctools_sdlplugin_Utils_chDir
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
